config_version: 1.0
training:
  trainer: base_trainer
  seed: 7664015
  experiment_name: run
  max_updates: 22000
  max_epochs: null
  log_interval: 100
  logger_level: info
  log_format: json
  log_detailed_config: true
  should_not_log: false
  tensorboard: false
  batch_size: 128
  num_workers: 4
  fast_read: false
  dataset_size_proportional_sampling: true
  pin_memory: false
  checkpoint_interval: 1000
  evaluation_interval: 1000
  clip_gradients: false
  clip_norm_mode: all
  early_stop:
    enabled: false
    patience: 4000
    criteria: hateful_memes/roc_auc
    minimize: false
  lr_scheduler: true
  lr_steps: []
  lr_ratio: 0.1
  use_warmup: false
  warmup_factor: 0.2
  warmup_iterations: 1000
  device: cuda
  local_rank: null
  verbose_dump: true
  find_unused_parameters: false
  evaluate_metrics: true
evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
  predict: true
  predict_file_format: csv
model_config:
  unimodal_text:
    bert_model_name: bert-base-uncased
    freeze_base: false
    finetune_lr_multiplier: 1
    text_hidden_size: 768
    num_labels: 2
    text_encoder:
      type: transformer
      params:
        operator: sum
        embedding_params:
          type: vocab
          params:
            type: intersected
            embedding_name: glove.6B.300d
            embedding_dim: 300
            data_dir: /home/jupyter/meme_hateful_detection/data/raw
            vocab_file: vocabs/vocabulary_100k.txt
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false
    classifier:
      type: mlp
      params:
        in_dim: 768
        out_dim: 2
        hidden_dim: 768
        num_layers: 2
    losses:
    - type: cross_entropy
    model: unimodal_text
dataset_config:
  hateful_memes:
    data_dir: /home/jupyter/meme_hateful_detection/data/raw/datasets
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    images:
      train:
      - hateful_memes/defaults/images/
      val:
      - hateful_memes/defaults/images/
      test:
      - hateful_memes/defaults/images/
    features:
      train:
      - hateful_memes/defaults/features/detectron.lmdb
      val:
      - hateful_memes/defaults/features/detectron.lmdb
      test:
      - hateful_memes/defaults/features/detectron.lmdb
    annotations:
      train:
      - hateful_memes/defaults/annotations/train.jsonl
      val:
      - hateful_memes/defaults/annotations/dev.jsonl
      test:
      - hateful_memes/defaults/annotations/test.jsonl
    max_features: 100
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: hateful_memes/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
      bbox_processor:
        type: bbox
        params:
          max_length: 50
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
          - type: Resize
            params:
              size:
              - 256
              - 256
          - type: CenterCrop
            params:
              size:
              - 224
              - 224
          - ToTensor
          - GrayScaleTo3Channels
          - type: Normalize
            params:
              mean:
              - 0.46777044
              - 0.44531429
              - 0.40661017
              std:
              - 0.12221994
              - 0.12145835
              - 0.14380469
    return_features_info: false
datasets: hateful_memes
model: unimodal_text
config: configs/unimodal/bert_custom.yaml
run_type: train_inference
optimizer:
  type: adam_w
  params:
    lr: 5.0e-05
    eps: 1.0e-08
scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 22000
env:
  cache_dir: /home/jupyter/.cache/torch/mmf
  dataset_zoo: configs/zoo/datasets.yaml
  model_zoo: configs/zoo/models.yaml
  data_dir: /home/jupyter/meme_hateful_detection/data/raw
  save_dir: /home/jupyter/meme_hateful_detection/save/unimodal_text
  log_dir: /home/jupyter/meme_hateful_detection/save/logs
  report_dir: /home/jupyter/meme_hateful_detection/save/reports
  tensorboard_logdir: ''
  user_dir: /home/jupyter/meme_hateful_detection
distributed:
  init_method: null
  rank: 0
  port: -1
  backend: nccl
  world_size: 1
  no_spawn: false
checkpoint:
  resume: false
  resume_file: null
  resume_best: false
  resume_pretrained: false
  resume_zoo: null
  zoo_config_override: false
  pretrained_state_mapping:
    base: base
  save_git_details: true
  reset:
    all: false
    optimizer: false
    counts: false
start_rank: 0
device_id: 0
