includes:
- ./defaults.yaml
- configs/models/mmbt/with_features.yaml
- configs/datasets/hateful_memes/with_features.yaml

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8
    
training:
  tensorboard: true
  
env:
  cache_dir: ${resolve_cache_dir:MMF_CACHE_DIR}
  data_dir: ${resolve_dir:MMF_DATA_DIR, data}
  save_dir: ${env:MMF_SAVE_DIR, ./save}
  log_dir: ${env:MMF_LOG_DIR,}
  report_dir: ${env:MMF_REPORT_DIR,}
  tensorboard_logdir: ${env:MMF_TENSORBOARD_LOGDIR,}