includes:
- ./text.yaml
- configs/datasets/hateful_memes/bert.yaml
- configs/models/unimodal/bert.yaml

model_config:
  unimodal_text:
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
  predict: true
  predict_file_format: csv

training:
  batch_size: 32
  log_interval: 100
  log_format: json
  log_detailed_config: true
  evaluate_metrics: true
  verbose_dump: true
  tensorboard: true
  
env:
  cache_dir: ${resolve_cache_dir:MMF_CACHE_DIR}
  data_dir: ${resolve_dir:MMF_DATA_DIR, data}
  save_dir: ${env:MMF_SAVE_DIR, ./save}
  log_dir: ${env:MMF_LOG_DIR,}
  report_dir: ${env:MMF_REPORT_DIR,}
  tensorboard_logdir: ${env:MMF_TENSORBOARD_LOGDIR,}