model_config:
  unimodal_image:
    classifier:
      type: mlp
      params:
        num_layers: 2
    losses:
    - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
  predict: true
  predict_file_format: csv

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false
  log_interval: 100
  log_format: json
  log_detailed_config: true
  checkpoint_interval: 1000
  evaluation_interval: 1000
  clip_gradients: false
  clip_norm_mode: all
  evaluate_metrics: true
  verbose_dump: true

checkpoint:
  pretrained_state_mapping:
    base: base